### ISSUE TITLE
PivotTable does not output a pure table

### ISSUE THREAD

**Issue by comphonia** [Click2Buy/vue-pivot-table#43]
The PivotTable outputs a table nested in 2 divs
```html
<div class="position-relative" default-show-settings="true">
  <div class="table-responsive">
    <table class="table table-bordered">
      ...
    </table>
  </div>
</div>
```
Is there a way to get just the table component without having to mess with the DOM?

**Comment by antoinematyja** [comment]
Hi, thanks for filing this issue.

It makes sense as the component should render as a table, but as you can see in the component:
https://github.com/Click2Buy/vue-pivot-table/blob/master/src/components/PivotTable.vue

The component has loading feedback/"no data" warning message that shouldn't be rendered as a table. Since Vue does not allow multiple root nodes, if the root node is a table then these cases should render inside the table too.

I could render these in an empty table but I'm not sure of the benefits of doing so? Let me know if I missed something.

Thanks

**Comment by comphonia** [comment]
@antoinematyja Oh, I see. It'll probably be better to fork and modify it for my use case. Thanks!
